In [40]:
import pandas as pd 
import numpy as np

# load dataset 

df = pd.read_csv("IMDB Dataset.csv")
df = df.sample(5000)
df.head()

,review,sentiment
25872,This is a film that belongs firmly to the 50's...,negative
30505,The thing that really gets me about this movie...,negative
17032,Just watched this early Bugs Bunny (first time...,positive
27184,While driving in a highway to the wedding of h...,positive
39311,"Don't get me wrong. I really love the ""arena-m...",negative


In [41]:
print(df.shape)
print(df['sentiment'].value_counts())

(5000, 2)
sentiment
positive    2532
negative    2468
Name: count, dtype: int64


In [42]:
import re 
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "",text)    # remove URLs
    text = re.sub(r"[^a-zA-Z\s]", "",text)   # remove special characters
    tokens = text.split()

    tokens = [word for word in tokens if word not in stop_words]
    tokens = [lemmatizer.lemmatize(word) for word in tokens ]

    return " ".join(tokens)

df['clean_text'] = df['review'].apply(preprocess_text)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [43]:
from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer()
X_bow = bow.fit_transform(df['clean_text'])


In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(df['clean_text'])

In [45]:
from sklearn.model_selection import train_test_split

y = df['sentiment']

X_train,X_test,y_train,y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)

In [46]:
from  sklearn.linear_model import LogisticRegression 

lr = LogisticRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

In [47]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(X_train, y_train)

y_pred_nb = nb.predict(X_test)


In [48]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

# Classification Report

In [53]:
from sklearn.metrics import classification_report

print("Logistic Regression:\n", classification_report(y_test,y_pred_lr))
print("Navie Bayes:\n", classification_report(y_test,y_pred_nb))
print("Decision Tree:\n", classification_report(y_test,y_pred_dt))

Logistic Regression:
               precision    recall  f1-score   support

    negative       0.88      0.84      0.86       483
    positive       0.85      0.89      0.87       517

    accuracy                           0.86      1000
   macro avg       0.87      0.86      0.86      1000
weighted avg       0.87      0.86      0.86      1000

Navie Bayes:
               precision    recall  f1-score   support

    negative       0.84      0.88      0.86       483
    positive       0.88      0.85      0.86       517

    accuracy                           0.86      1000
   macro avg       0.86      0.86      0.86      1000
weighted avg       0.86      0.86      0.86      1000

Decision Tree:
               precision    recall  f1-score   support

    negative       0.67      0.71      0.69       483
    positive       0.71      0.67      0.69       517

    accuracy                           0.69      1000
   macro avg       0.69      0.69      0.69      1000
weighted avg       0.6

# Confusion Matrix

In [54]:
from sklearn.metrics import classification_report, confusion_matrix

print("Logistic Regression Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_lr))

print("\nNaive Bayes Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_nb))

print("\nDecision Tree Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))


Logistic Regression Confusion Matrix:
[[404  79]
 [ 56 461]]

Naive Bayes Confusion Matrix:
[[424  59]
 [ 79 438]]

Decision Tree Confusion Matrix:
[[341 142]
 [169 348]]
